# Generated by Django 3.2.3 on 2021-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produtoid', models.AutoField(db_column='produtoID', primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigobarra', models.CharField(blank=True, max_length=15, null=True)),
                ('tempoentrega', models.IntegerField(blank=True, null=True)),
                ('precorevenda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('imagemgrande', models.FileField(upload_to='images/product_images')),
                ('imagempequena', models.FileField(upload_to='images/product_images')),
                ('descontinuado', models.IntegerField(blank=True, null=True)),
                ('fornecedorid', models.IntegerField(blank=True, db_column='fornecedorID', null=True)),
                ('categoriaid', models.IntegerField(blank=True, db_column='categoriaID', null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': True,
            },
        ),
    ]
