# Generated by Django 3.2.3 on 2021-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produtoid', models.AutoField(db_column='produtoID', primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigobarra', models.CharField(blank=True, max_length=15, null=True)),
                ('tempoentrega', models.SmallIntegerField(blank=True, null=True)),
                ('precorevenda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('imagemgrande', models.CharField(max_length=100)),
                ('imagempequena', models.CharField(max_length=100)),
                ('fornecedorid', models.SmallIntegerField(blank=True, db_column='fornecedorID', null=True)),
                ('categoriaid', models.SmallIntegerField(blank=True, db_column='categoriaID', null=True)),
            ],
            options={
                'verbose_name': 'Produto do Fornecedor',
                'verbose_name_plural': 'Produtos Disponíveis (Fornecedores)',
                'db_table': 'produtos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProdutosClientes',
            fields=[
                ('produtoid', models.AutoField(db_column='produtoID', primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigobarra', models.CharField(blank=True, max_length=15, null=True)),
                ('tempoentrega', models.SmallIntegerField(blank=True, null=True)),
                ('precorevenda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('imagemgrande', models.CharField(max_length=100)),
                ('imagempequena', models.CharField(max_length=100)),
                ('descontinuado', models.SmallIntegerField(blank=True, null=True)),
                ('fornecedorid', models.SmallIntegerField(blank=True, db_column='fornecedorID', null=True)),
                ('categoriaid', models.SmallIntegerField(blank=True, db_column='categoriaID', null=True)),
            ],
            options={
                'verbose_name': 'Produto do Cliente',
                'verbose_name_plural': 'Produtos Disponíveis (Clientes)',
                'db_table': 'produtos_clientes',
                'managed': True,
            },
        ),
    ]
