# Generated by Django 2.2.5 on 2021-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listar_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagemgrande',
            field=models.FileField(upload_to='images/product_images'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagempequena',
            field=models.FileField(upload_to='images/product_images'),
        ),
    ]
