# Generated by Django 3.2.3 on 2021-05-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listar_produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='descontinuado',
        ),
    ]
