# Generated by Django 3.2.3 on 2021-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listar_produtos', '0002_remove_produtos_descontinuado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': True, 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos Disponíveis'},
        ),
    ]
