# Generated by Django 3.2.3 on 2021-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listar_produtos', '0003_alter_produtos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosClientes',
            fields=[
                ('produtoid', models.AutoField(db_column='produtoID', primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigobarra', models.CharField(blank=True, max_length=15, null=True)),
                ('tempoentrega', models.IntegerField(blank=True, null=True)),
                ('precorevenda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('imagemgrande', models.CharField(max_length=100)),
                ('imagempequena', models.CharField(max_length=100)),
                ('descontinuado', models.IntegerField(blank=True, null=True)),
                ('fornecedorid', models.IntegerField(blank=True, db_column='fornecedorID', null=True)),
                ('categoriaid', models.IntegerField(blank=True, db_column='categoriaID', null=True)),
            ],
            options={
                'verbose_name': 'Produto do Cliente',
                'verbose_name_plural': 'Produtos Disponíveis (Clientes)',
                'db_table': 'produtos_clientes',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': True, 'verbose_name': 'Produto do Fornecedor', 'verbose_name_plural': 'Produtos Disponíveis (Fornecedores)'},
        ),
    ]
