version: "3.3"

services:
  postgres_db:
    ports:
      - 15433:5432

  pgadmin:
    ports:
      - "8081:80"

  web:
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    extra_hosts:  # TODO to think about
      - "transportadoravietna.local:0.0.0.0"

