# Generated by Django 3.2.3 on 2021-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.AutoField(db_column='clienteID', primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoid', models.SmallIntegerField(blank=True, db_column='estadoID', null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('telefone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('senha', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Lista de Clientes',
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('fornecedorid', models.AutoField(db_column='fornecedorID', primary_key=True, serialize=False)),
                ('nomefornecedor', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoid', models.SmallIntegerField(blank=True, db_column='estadoID', null=True)),
                ('ddd', models.SmallIntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('senha', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Lista de Fornecedores',
                'db_table': 'fornecedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FornecedoresContatos',
            fields=[
                ('contatoid', models.AutoField(db_column='contatoID', primary_key=True, serialize=False)),
                ('fornecedorid', models.IntegerField(blank=True, db_column='fornecedorID', null=True)),
                ('departamentoid', models.IntegerField(blank=True, db_column='departamentoID', null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Contato do Fornecedor',
                'verbose_name_plural': 'Contatos dos Fornecedores',
                'db_table': 'fornecedores_contatos',
                'managed': True,
            },
        ),
    ]
