# Generated by Django 3.2.3 on 2021-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': True, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Lista de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'managed': True, 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Lista de Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='fornecedorescontatos',
            options={'managed': True, 'verbose_name': 'Contato do Fornecedor', 'verbose_name_plural': 'Contatos dos Fornecedores'},
        ),
    ]
