# Generated by Django 3.2.3 on 2021-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquias',
            fields=[
                ('franquiaid', models.AutoField(db_column='franquiaID', primary_key=True, serialize=False)),
                ('nomegerente', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estadoid', models.IntegerField(db_column='estadoID')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('dataabertura', models.DateField()),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'franquias',
                'managed': True,
            },
        ),
    ]
