# Generated by Django 2.2.5 on 2021-05-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedidoid', models.AutoField(db_column='pedidoID', primary_key=True, serialize=False)),
                ('clienteid', models.IntegerField(db_column='clienteID')),
                ('transportadoraid', models.IntegerField(blank=True, db_column='transportadoraID', null=True)),
                ('data_pedido', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status_pedido', models.IntegerField()),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conhecimento', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidosItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidoid', models.IntegerField(blank=True, db_column='pedidoID', null=True)),
                ('produtoid', models.IntegerField(blank=True, db_column='produtoID', null=True)),
                ('precounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidosStatus',
            fields=[
                ('statusid', models.AutoField(db_column='statusID', primary_key=True, serialize=False)),
                ('nomestatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pedidos_status',
                'managed': True,
            },
        ),
    ]
