# Generated by Django 2.2.5 on 2021-05-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidosstatus',
            options={'managed': False},
        ),
    ]
