# Generated by Django 3.2.3 on 2021-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_pedidos', '0002_auto_20210519_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidositem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
