# Generated by Django 3.2.3 on 2021-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_pedidos', '0004_alter_pedidos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'managed': True, 'ordering': ('pedidoid', 'data_pedido', 'status_pedido', 'valor_pedido'), 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidositem',
            options={'managed': True, 'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Items dos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidosstatus',
            options={'managed': True, 'verbose_name': 'Status do Pedido', 'verbose_name_plural': 'Status dos Pedidos'},
        ),
    ]
