# Generated by Django 3.2.3 on 2021-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.AutoField(db_column='clienteID', primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoid', models.IntegerField(blank=True, db_column='estadoID', null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('telefone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('senha', models.CharField(blank=True, max_length=10, null=True)),
                ('nivel', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
    ]
