# Generated by Django 2.2.5 on 2021-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoriaid', models.AutoField(db_column='categoriaID', primary_key=True, serialize=False)),
                ('nomecategoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoid', models.AutoField(db_column='departamentoID', primary_key=True, serialize=False)),
                ('nomedepartamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estadoid', models.AutoField(db_column='estadoID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('sigla', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'estados',
                'managed': True,
            },
        ),
    ]
