# Generated by Django 3.2.3 on 2021-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': True, 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': True, 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': True, 'verbose_name': 'Estado', 'verbose_name_plural': 'Lista de Estados'},
        ),
    ]
