# Generated by Django 2.2.5 on 2021-05-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadoras',
            fields=[
                ('transportadoraid', models.AutoField(db_column='transportadoraID', primary_key=True, serialize=False)),
                ('nometransportadora', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoid', models.IntegerField(blank=True, db_column='estadoID', null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 'transportadoras',
                'managed': True,
            },
        ),
    ]
