# Generated by Django 3.2.3 on 2021-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listar_transportadoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportadoras',
            options={'managed': True, 'verbose_name': 'Transportadora', 'verbose_name_plural': 'Transportadoras Disponíveis'},
        ),
    ]
